"""empty message

Revision ID: 066a15d5f112
Revises: fd1a7e8621fa
Create Date: 2025-02-03 18:59:41.637552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066a15d5f112'
down_revision: Union[str, None] = 'fd1a7e8621fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('name', sa.String(length=32), nullable=False))
    op.add_column('clients', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('clients', sa.Column('date_from', sa.String(length=20), nullable=False))
    op.add_column('clients', sa.Column('date_to', sa.String(length=20), nullable=False))
    op.drop_column('clients', 'client_date_from')
    op.drop_column('clients', 'client_price')
    op.drop_column('clients', 'client_date_to')
    op.drop_column('clients', 'client_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('client_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('client_date_to', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('client_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('client_date_from', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('clients', 'date_to')
    op.drop_column('clients', 'date_from')
    op.drop_column('clients', 'price')
    op.drop_column('clients', 'name')
    # ### end Alembic commands ###
