"""empty message

Revision ID: 07b17dae1b5f
Revises: 5de0f5794e0f
Create Date: 2025-02-11 17:32:20.621001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b17dae1b5f'
down_revision: Union[str, None] = '5de0f5794e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_marzban_request', sa.Date(), nullable=True))
    op.drop_column('users', 'last_marzban_request_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_marzban_request_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_marzban_request')
    # ### end Alembic commands ###
