"""empty message

Revision ID: 0a49497311f7
Revises: cf7b5e7dd327
Create Date: 2025-02-11 16:07:50.416154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a49497311f7'
down_revision: Union[str, None] = 'cf7b5e7dd327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_marzban_request_date', sa.Date(), nullable=True))
    op.drop_column('users', 'last_marzban_request')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_marzban_request', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_marzban_request_date')
    # ### end Alembic commands ###
