"""empty message

Revision ID: 0eb2c9a3015e
Revises: 1025640b3afa
Create Date: 2025-03-02 12:56:20.920077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb2c9a3015e'
down_revision: Union[str, None] = '1025640b3afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'downloads_today')
    op.drop_column('users', 'last_download_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_download_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('downloads_today', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
