"""empty message

Revision ID: 36314f1804cf
Revises: fbb6f65c95cc
Create Date: 2025-02-04 21:09:56.538684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36314f1804cf'
down_revision: Union[str, None] = 'fbb6f65c95cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'date_from',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('clients', 'date_to',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'date_to',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('clients', 'date_from',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
