"""empty message

Revision ID: 44cdf207be21
Revises: a6200769afb5
Create Date: 2025-01-31 19:06:51.510086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44cdf207be21'
down_revision: Union[str, None] = 'a6200769afb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lines_table_id_fkey', 'lines', type_='foreignkey')
    op.create_foreign_key(None, 'lines', 'tables', ['table_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.create_foreign_key('lines_table_id_fkey', 'lines', 'tables', ['table_id'], ['id'])
    # ### end Alembic commands ###
