"""empty message

Revision ID: 4d776b7150aa
Revises: 29c6c8968712
Create Date: 2025-02-24 15:04:40.002828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d776b7150aa'
down_revision: Union[str, None] = '29c6c8968712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('tg_username', sa.String(length=32), nullable=False))
    op.drop_constraint('connections_client_id_fkey', 'connections', type_='foreignkey')
    op.drop_column('connections', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('connections_client_id_fkey', 'connections', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_column('connections', 'tg_username')
    # ### end Alembic commands ###
