"""empty message

Revision ID: 50d60d75627c
Revises: 49916f14fe73
Create Date: 2025-02-25 17:49:33.040522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d60d75627c'
down_revision: Union[str, None] = '49916f14fe73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('username', sa.String(length=32), nullable=False))
    op.drop_constraint('clients_table_id_fkey', 'clients', type_='foreignkey')
    op.drop_column('clients', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.create_foreign_key('clients_table_id_fkey', 'clients', 'tables', ['table_id'], ['id'], ondelete='CASCADE')
    op.drop_column('clients', 'username')
    # ### end Alembic commands ###
