"""empty message

Revision ID: 58b5ff44ed8c
Revises: a5cdbf4e4ef3
Create Date: 2025-02-24 15:11:56.931698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b5ff44ed8c'
down_revision: Union[str, None] = 'a5cdbf4e4ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('tg_id', sa.Integer(), nullable=False))
    op.drop_constraint('connections_client_id_fkey', 'connections', type_='foreignkey')
    op.drop_column('connections', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('connections_client_id_fkey', 'connections', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_column('clients', 'tg_id')
    # ### end Alembic commands ###
