"""empty message

Revision ID: 5a64449a3bda
Revises: 3ebbe78e0444
Create Date: 2025-02-04 19:18:14.040549

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a64449a3bda"
down_revision: Union[str, None] = "3ebbe78e0444"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("days_late", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "days_late")
    # ### end Alembic commands ###
