"""empty message

Revision ID: 5c401b3e180c
Revises: d09d22d9f4ff
Create Date: 2025-02-24 14:28:41.496340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c401b3e180c'
down_revision: Union[str, None] = 'd09d22d9f4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'days_late')
    op.add_column('connections', sa.Column('days_late', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'days_late')
    op.add_column('clients', sa.Column('days_late', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
