"""empty message

Revision ID: 5de0f5794e0f
Revises: c084af63efab
Create Date: 2025-02-11 17:28:16.475602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de0f5794e0f'
down_revision: Union[str, None] = 'c084af63efab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'downloads_today',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'marzban_requests_today',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'marzban_requests_today',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'downloads_today',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
