"""empty message

Revision ID: 62addb531369
Revises: 75cfc631054a
Create Date: 2025-02-24 16:01:28.008403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62addb531369'
down_revision: Union[str, None] = '75cfc631054a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('date_to', sa.Date(), nullable=False))
    op.drop_column('connections', 'months')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('months', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('connections', 'date_to')
    # ### end Alembic commands ###
