"""empty message

Revision ID: a5cdbf4e4ef3
Revises: 4d776b7150aa
Create Date: 2025-02-24 15:09:59.317363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5cdbf4e4ef3'
down_revision: Union[str, None] = '4d776b7150aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'connections', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.drop_column('connections', 'client_id')
    # ### end Alembic commands ###
