"""empty message

Revision ID: a8a630e48929
Revises: d36b3cd2af33
Create Date: 2025-02-11 18:00:27.663456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a630e48929'
down_revision: Union[str, None] = 'd36b3cd2af33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'downloads_today',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'marzban_requests_today',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'marzban_requests_today',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'downloads_today',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
