"""empty message

Revision ID: ab826cd169f8
Revises: a8a630e48929
Create Date: 2025-02-24 13:50:02.361730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab826cd169f8'
down_revision: Union[str, None] = 'a8a630e48929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('months', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'months')
    # ### end Alembic commands ###
