"""empty message

Revision ID: c084af63efab
Revises: 0a49497311f7
Create Date: 2025-02-11 16:41:15.475092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c084af63efab'
down_revision: Union[str, None] = '0a49497311f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('tg_username', sa.String(length=32), nullable=False))
    op.drop_column('connections', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('nickname', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('connections', 'tg_username')
    # ### end Alembic commands ###
