"""empty message

Revision ID: cb0739f1ce23
Revises: 
Create Date: 2025-02-03 18:22:28.458206

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb0739f1ce23"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tg_id"),
    )
    op.create_table(
        "tables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_tg_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["owner_tg_id"], ["users.tg_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=True),
        sa.Column("client_name", sa.String(length=32), nullable=False),
        sa.Column("client_price", sa.Integer(), nullable=False),
        sa.Column("client_date_from", sa.String(length=20), nullable=False),
        sa.Column("client_date_to", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["table_id"], ["tables.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lines")
    op.drop_table("tables")
    op.drop_table("users")
    # ### end Alembic commands ###
