"""empty message

Revision ID: cf7b5e7dd327
Revises: dbeb41d9fe0a
Create Date: 2025-02-11 15:35:37.630569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7b5e7dd327'
down_revision: Union[str, None] = 'dbeb41d9fe0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'downloads_today',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'marzban_requests_today',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'marzban_requests_today',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'downloads_today',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
