"""empty message

Revision ID: cfe5ed0e4bbb
Revises: 22f4597cfc1c
Create Date: 2025-01-29 18:48:26.094524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe5ed0e4bbb'
down_revision: Union[str, None] = '22f4597cfc1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tables', 'name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
