"""empty message

Revision ID: d09d22d9f4ff
Revises: ab826cd169f8
Create Date: 2025-02-24 14:23:08.464512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09d22d9f4ff'
down_revision: Union[str, None] = 'ab826cd169f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'date_to')
    op.drop_column('clients', 'price')
    op.drop_column('clients', 'date_from')
    op.add_column('connections', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'price')
    op.add_column('clients', sa.Column('date_from', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('date_to', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
