"""empty message

Revision ID: d36b3cd2af33
Revises: 07b17dae1b5f
Create Date: 2025-02-11 17:36:42.182200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36b3cd2af33'
down_revision: Union[str, None] = '07b17dae1b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'downloads_today',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'downloads_today',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
