"""empty message

Revision ID: dbeb41d9fe0a
Revises: f0b47b1fa784
Create Date: 2025-02-11 15:29:40.101375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbeb41d9fe0a'
down_revision: Union[str, None] = 'f0b47b1fa784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('marzban_requests_today', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_marzban_request', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_marzban_request')
    op.drop_column('users', 'marzban_requests_today')
    # ### end Alembic commands ###
