"""empty message

Revision ID: f0b47b1fa784
Revises: 9e13dc241363
Create Date: 2025-02-10 14:44:38.664057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b47b1fa784'
down_revision: Union[str, None] = '9e13dc241363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('user_tg_id', sa.BigInteger(), nullable=True))
    op.alter_column('connections', 'link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('connections_user_id_fkey', 'connections', type_='foreignkey')
    op.create_foreign_key(None, 'connections', 'users', ['user_tg_id'], ['tg_id'], ondelete='CASCADE')
    op.drop_column('connections', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.create_foreign_key('connections_user_id_fkey', 'connections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('connections', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('connections', 'user_tg_id')
    # ### end Alembic commands ###
