"""empty message

Revision ID: fd1a7e8621fa
Revises: f0e6287cd7a6
Create Date: 2025-02-03 18:59:08.641207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1a7e8621fa'
down_revision: Union[str, None] = 'f0e6287cd7a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=32), nullable=False),
    sa.Column('client_price', sa.Integer(), nullable=False),
    sa.Column('client_date_from', sa.String(length=20), nullable=False),
    sa.Column('client_date_to', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lines')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('client_price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_date_from', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('client_date_to', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name='lines_table_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='lines_pkey')
    )
    op.drop_table('clients')
    # ### end Alembic commands ###
