services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
    ports:
      - "5000:5000"

  db:
    image: postgres:17
    env_file:
      - .env 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  marzban:
    image: gozargah/marzban:latest
    container_name: marzban_marzban_1
    networks:
      - my_network
    ports:
      - "8001:8000"

volumes:
  postgres_data:
