services:
  vpn_bot:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
    network_mode: host

  vpn_db:
    image: postgres:17
    env_file:
      - .env 
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
