windows_os_text = "🖥 Windows"
android_os_text = "📱Android"
mac_os_text = "💻 MacOS"
ios_os_text = "🍎 IOS"
android_tv_os_text = "📺 AndroidTV" 

get_new_connection_text = "📡 Подключиться"
get_instruction_text = "📘 Инструкции"
renew_subscribtion_text = "💶 Продлить"
my_connections_text = "🏠 Мои подключения"

one_month_text = "1 мес. - 150₽"
three_month_text = "3 мес. - 400₽"
six_month_text = "🔥6 мес. - 750₽"
twelve_month_text = "12 мес. - 1300₽"