adding_data_error = "❌ Произошла ошибка при добавлении данных."
clients_does_not_exists_error  = "❌ У вас нет клиентов."
connections_do_not_exist_error= "❌ У вас нет подключений."
connection_does_not_exist_error = "❌ Такого подключения не существует."
client_does_not_exists_error = "❌ Такого клиента не существует."
marzban_user_add_error = '❌ Ошибка при создании ключа доступа.'
marzban_link_get_error = "❌ Ошибка при выдаче ключа доступа."
excel_table_can_not_create_error = '❌ Ошибка при скачивании таблицы.'
refunded_error = "❌ Неверная команда или номер операции."
payment_error = "❌ Ошибка платежа. Свяжитесь с администратором."
